/**
 * Repurpose generation domain library.
 *
 * Converts an existing content source into one of six bounded output formats.
 * Every generated draft is labelled draft-only; no output is automatically
 * publishable. Fabricated facts, invented sources, and first-person claims are
 * explicitly forbidden in every prompt.
 */

import { DEFAULT_COPY_MODEL } from "./article-generation";

// ---------------------------------------------------------------------------
// Output options — exactly six, each with a stable code and a one-line promise
// ---------------------------------------------------------------------------

export const REPURPOSE_OUTPUT_OPTIONS = [
  {
    value: "seo_blog_article" as const,
    label: "SEO blog article",
    promise: "A focused, evidence-backed article optimised for organic search.",
  },
  {
    value: "linkedin_post" as const,
    label: "LinkedIn post",
    promise: "A concise professional post that surfaces one insight for a business audience.",
  },
  {
    value: "x_thread" as const,
    label: "X thread",
    promise: "A numbered thread of punchy, self-contained tweets that unfold a single idea.",
  },
  {
    value: "email" as const,
    label: "Email",
    promise: "A plain-text subscriber email with a clear subject line and one call to action.",
  },
  {
    value: "faq" as const,
    label: "FAQ",
    promise: "A structured set of questions and direct answers drawn from the source.",
  },
  {
    value: "outline" as const,
    label: "Outline",
    promise: "A hierarchical working outline that maps the source into a fresh article structure.",
  },
] as const;

export type RepurposeOutput = typeof REPURPOSE_OUTPUT_OPTIONS[number]["value"];

/** Runtime type guard: returns true and narrows to RepurposeOutput for valid codes. */
export function isRepurposeOutput(value: unknown): value is RepurposeOutput {
  return typeof value === "string" &&
    REPURPOSE_OUTPUT_OPTIONS.some((option) => option.value === value);
}

export const REPURPOSE_SOURCE_MODES = ["file", "url", "paste"] as const;
export type RepurposeSourceMode = typeof REPURPOSE_SOURCE_MODES[number];

export function isRepurposeSourceMode(value: unknown): value is RepurposeSourceMode {
  return typeof value === "string"
    && REPURPOSE_SOURCE_MODES.some((mode) => mode === value);
}

// ---------------------------------------------------------------------------
// Source types
// ---------------------------------------------------------------------------

/** Raw text extracted from any content source (URL, PDF, paste, etc.). */
export type RepurposeSource = {
  /** The extracted plain text. Callers should extract before passing in. */
  text: string;
  /** Optional human-readable label (URL, file name, page title, etc.). */
  attribution?: string;
};

// ---------------------------------------------------------------------------
// Stage / lifecycle types
// ---------------------------------------------------------------------------

/**
 * The four upload-to-ready pipeline stages for a repurpose job.
 * Publishing is outside this feature; stages stop at ready.
 */
export type RepurposeStage =
  | "uploading"
  | "reading"
  | "writing"
  | "ready";

/** Maps a stage value to a display label. */
export function repurposeStageLabel(stage: RepurposeStage): string {
  switch (stage) {
    case "uploading": return "Uploading";
    case "reading": return "Reading";
    case "writing": return "Writing";
    case "ready": return "Ready";
  }
}

// ---------------------------------------------------------------------------
// Draft type
// ---------------------------------------------------------------------------

export type RepurposeDraft = {
  output: RepurposeOutput;
  /** Short title / subject line generated by the model. */
  title: string;
  /** Full body in Markdown. May be single-paragraph prose or structured text. */
  bodyMarkdown: string;
  /** One-sentence excerpt / preview (≤ 200 characters). */
  excerpt: string;
};

// ---------------------------------------------------------------------------
// Safe parsing helpers
// ---------------------------------------------------------------------------

/** Returns the value as a plain object or an empty object. */
export function safeRecord(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? (value as Record<string, unknown>)
    : {};
}

/** Returns the value as a string or an empty string. */
export function safeString(value: unknown): string {
  return typeof value === "string" ? value.trim() : "";
}

/** Returns the value as a number or the provided default. */
export function safeNumber(value: unknown, fallback = 0): number {
  return typeof value === "number" && Number.isFinite(value) ? value : fallback;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/** Clips a string to a maximum character length. */
function clip(value: string, max = 4000): string {
  return value.trim().slice(0, max);
}

/** Returns the label for a given output code. */
export function repurposeOutputLabel(output: RepurposeOutput): string {
  return REPURPOSE_OUTPUT_OPTIONS.find((option) => option.value === output)?.label ?? output;
}

/** Returns the one-line promise for a given output code. */
export function repurposeOutputPromise(output: RepurposeOutput): string {
  return REPURPOSE_OUTPUT_OPTIONS.find((option) => option.value === output)?.promise ?? "";
}

// ---------------------------------------------------------------------------
// Format-specific constraints injected into the prompt
// ---------------------------------------------------------------------------

function formatConstraints(output: RepurposeOutput): string {
  switch (output) {
    case "seo_blog_article":
      // Aligns with Rebound SEO Content Studio policy (matches article-generation):
      // target 2,300–2,800 words so the finished draft clears the 2,000-word
      // floor; exactly 6–8 H2 sections with useful H3 children.
      return [
        "- Length: target 2,300–2,800 words so the finished draft clears the 2,000-word floor; never pad.",
        "- Structure: one H1, exactly 6–8 H2 sections, useful H3 children under each H2 where they clarify a real subtopic.",
        "- Do not invent statistics; reference only claims found in the source text.",
        "- Write in second-person where natural; no first-person experience.",
        "- Include a focused introduction, keyword-led H2s, and a conclusion with one clear next action.",
        "- Every factual claim must trace to the supplied source text.",
      ].join("\n");

    case "linkedin_post":
      return [
        "- Length: 150–300 words.",
        "- Open with a single punchy hook sentence (no 'I' opener).",
        "- Use short paragraphs; add 3–5 relevant hashtags at the end.",
        "- One clear takeaway; no invented testimonials or results.",
        "- Do not mention the author's personal experience or opinions unless sourced.",
      ].join("\n");

    case "x_thread":
      return [
        "- Produce 5–10 numbered tweets (1/, 2/, …).",
        "- Each tweet ≤ 280 characters including the number prefix.",
        "- Tweet 1 must hook the reader without being clickbait.",
        "- Last tweet should state a clear action or key takeaway.",
        "- No invented statistics; draw only from the supplied source text.",
      ].join("\n");

    case "email":
      return [
        "- Provide a subject line (≤ 60 characters) and a preheader (≤ 100 characters).",
        "- Body: 200–400 words of plain prose, no HTML markup.",
        "- One call to action at the end; do not invent URLs.",
        "- Salutation: 'Hi [First name],' — never use a specific name.",
        "- No first-person claims; attribute facts to the source.",
      ].join("\n");

    case "faq":
      return [
        "- Produce 5–8 question-and-answer pairs.",
        "- Each question should be a complete sentence ending with '?'.",
        "- Each answer: 40–120 words, direct and specific.",
        "- Questions must be grounded in the source text; do not invent topics.",
        "- Format: '**Q: …**\\n\\nA: …' for each pair.",
      ].join("\n");

    case "outline":
      return [
        "- Provide a title, then H2 sections with H3 bullet points under each.",
        "- 4–8 top-level sections; 2–5 sub-points per section.",
        "- Each sub-point is a short phrase (≤ 12 words), not a full sentence.",
        "- Reflect the source structure; do not add topics not present in the source.",
        "- No prose paragraphs; outline nodes only.",
      ].join("\n");
  }
}

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

/**
 * Maximum characters of source text embedded in the prompt.
 * 60,000 characters allows long supported sources (full articles, reports,
 * transcripts) to be meaningfully used while remaining bounded.
 */
export const SOURCE_TEXT_LIMIT = 60_000;

export type RepurposePromptOptions = {
  source: RepurposeSource;
  /** Business name and brief description for context. */
  businessContext: string;
  /** Approved target keyword — optional, bounded to 300 chars. */
  targetKeyword?: string;
  output: RepurposeOutput;
};

export function buildRepurposePrompt(options: RepurposePromptOptions): string {
  const { source, businessContext, targetKeyword, output } = options;

  const boundedSource = clip(source.text, SOURCE_TEXT_LIMIT);
  const attribution = source.attribution ? clip(source.attribution, 300) : "Unspecified source";
  const boundedBusiness = clip(businessContext, 500);
  const boundedKeyword = targetKeyword ? clip(targetKeyword.trim(), 300) : "";
  const outputLabel = repurposeOutputLabel(output);
  const outputPromise = repurposeOutputPromise(output);
  const constraints = formatConstraints(output);

  const keywordSection = boundedKeyword
    ? `APPROVED TARGET KEYWORD\n${boundedKeyword}\nInclude this keyword naturally where it fits; do not force it.\n`
    : "APPROVED TARGET KEYWORD\nNone supplied. Do not invent or assume a keyword.\n";

  return `You are Rebound SEO's evidence-safe content repurposing engine.
Your job is to transform supplied source text into one carefully bounded draft for human review.

CRITICAL RULES — NEVER VIOLATE THESE
1. This output is a DRAFT ONLY. Label nothing as final or ready to publish.
2. NEVER fabricate facts, statistics, data points, or claims not present in the source text.
3. NEVER invent sources, citations, URLs, publication names, or study references.
4. NEVER write in first-person or imply personal experience (no "I", "we experienced", "in my view").
5. NEVER manufacture testimonials, quotes, case studies, or customer stories.
6. Every factual claim must be traceable to the supplied source text below.
7. Attribute information faithfully to: ${attribution}
8. If the source text does not contain enough information for a claim, omit the claim.

BUSINESS CONTEXT
${boundedBusiness}

${keywordSection}
OUTPUT FORMAT REQUESTED
Format: ${outputLabel}
Promise: ${outputPromise}

FORMAT-SPECIFIC CONSTRAINTS
${constraints}

SOURCE TEXT (use only this; do not supplement with outside knowledge for factual claims)
---
${boundedSource}
---
SOURCE ATTRIBUTION: ${attribution}

INSTRUCTIONS
- Transform the source text into a "${outputLabel}" draft.
- Stay faithful to the facts and ideas in the source; reframe and restructure, but do not embellish.
- Use only the business context for brand framing, not for factual claims unless the source confirms them.
- Do not repeat the raw source verbatim; synthesise and restructure it.
- Keep the draft tight; padding is worse than brevity.

Return ONLY a JSON object with this exact shape (no markdown fences, no commentary):
{
  "title": "short title or subject line (≤ 120 characters)",
  "bodyMarkdown": "full draft body in Markdown",
  "excerpt": "one-sentence preview of the draft (≤ 200 characters)"
}`;
}

// ---------------------------------------------------------------------------
// Anthropic request builder
// ---------------------------------------------------------------------------

export type RepurposeAnthropicRequest = {
  model: string;
  max_tokens: number;
  output_config: {
    format: {
      type: "json_schema";
      schema: Record<string, unknown>;
    };
  };
  messages: Array<{ role: string; content: string }>;
};

export function buildRepurposeAnthropicRequest(
  prompt: string,
  model = DEFAULT_COPY_MODEL,
): RepurposeAnthropicRequest {
  return {
    model,
    // 9,000 tokens matches article-generation; needed for SEO long-form output
    // (2,300–2,800 words + JSON envelope) and consistent with Content Studio policy.
    max_tokens: 9000,
    output_config: {
      format: {
        type: "json_schema",
        schema: {
          type: "object",
          additionalProperties: false,
          required: ["title", "bodyMarkdown", "excerpt"],
          properties: {
            title: { type: "string" },
            bodyMarkdown: { type: "string" },
            excerpt: { type: "string" },
          },
        },
      },
    },
    messages: [{ role: "user", content: prompt }],
  };
}

// ---------------------------------------------------------------------------
// Per-field size limits
// ---------------------------------------------------------------------------

export const REPURPOSE_LIMITS = {
  title: 120,
  excerpt: 200,
  /**
   * Soft cap on bodyMarkdown after generation.
   * 30,000 characters comfortably holds a 3,000-word SEO article
   * (≈ 6 chars/word × 3,000 words × overhead factor) without truncating
   * legitimate long-form output.
   */
  bodyMarkdown: 30_000,
} as const;

// ---------------------------------------------------------------------------
// Response parser / validator
// ---------------------------------------------------------------------------

export type RepurposeParseResult =
  | { ok: true; draft: RepurposeDraft }
  | { ok: false; error: string };

/**
 * Parses and validates a raw provider response into a RepurposeDraft.
 * Handles malformed JSON, missing fields, and over-limit values gracefully.
 */
export function parseRepurposeResponse(
  raw: unknown,
  output: RepurposeOutput,
): RepurposeParseResult {
  // Accept either a pre-parsed object or a raw JSON string
  let parsed: Record<string, unknown>;
  if (typeof raw === "string") {
    const trimmed = raw.trim();
    // Strip accidental markdown code fences if the model added them
    const stripped = trimmed.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "");
    try {
      const value = JSON.parse(stripped);
      parsed = safeRecord(value);
    } catch {
      return { ok: false, error: "Provider returned non-JSON output." };
    }
  } else {
    parsed = safeRecord(raw);
  }

  const title = safeString(parsed.title);
  const bodyMarkdown = safeString(parsed.bodyMarkdown);
  const excerpt = safeString(parsed.excerpt);

  if (!title) return { ok: false, error: "Provider response missing 'title' field." };
  if (!bodyMarkdown) return { ok: false, error: "Provider response missing 'bodyMarkdown' field." };
  if (!excerpt) return { ok: false, error: "Provider response missing 'excerpt' field." };

  // Apply per-field limits (hard truncation with indicator for title/excerpt;
  // soft truncation for bodyMarkdown)
  const clampedTitle = title.length > REPURPOSE_LIMITS.title
    ? title.slice(0, REPURPOSE_LIMITS.title - 1) + "…"
    : title;

  const clampedExcerpt = excerpt.length > REPURPOSE_LIMITS.excerpt
    ? excerpt.slice(0, REPURPOSE_LIMITS.excerpt - 1) + "…"
    : excerpt;

  const clampedBody = bodyMarkdown.length > REPURPOSE_LIMITS.bodyMarkdown
    ? bodyMarkdown.slice(0, REPURPOSE_LIMITS.bodyMarkdown)
    : bodyMarkdown;

  return {
    ok: true,
    draft: { output, title: clampedTitle, bodyMarkdown: clampedBody, excerpt: clampedExcerpt },
  };
}

// ---------------------------------------------------------------------------
// Handoff helpers
// ---------------------------------------------------------------------------

/**
 * Returns true only for the SEO blog article output, which can be opened in
 * Rebound SEO Content Studio for full editorial review and publishing.
 *
 * All other formats remain editable drafts only and never enter the Content
 * Studio publishing pipeline.
 */
export function canHandOffToContentStudio(output: RepurposeOutput): boolean {
  return output === "seo_blog_article";
}

/**
 * Returns the truthful handoff label for a given output.
 * - SEO blog articles: "Open in Content Studio"
 * - All other formats: "Keep as editable draft"
 */
export function repurposeHandoffLabel(output: RepurposeOutput): string {
  if (canHandOffToContentStudio(output)) {
    return "Open in Content Studio";
  }
  return "Keep as editable draft";
}
