import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createClient} from '@supabase/supabase-js';
const product=process.cwd();
const status=JSON.parse(execFileSync(product+'/node_modules/.bin/supabase',['status','-o','json'],{cwd:product,encoding:'utf8',stdio:['ignore','pipe','ignore']}));
if(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(status.API_URL))throw new Error('Local fixture only');
const db=createClient(status.API_URL,status.SERVICE_ROLE_KEY);
const fixture=JSON.parse(readFileSync(process.env.QA_LOCAL_BROWSER_FIXTURE!, 'utf8'));
const words='This is a synthetic test of an interview workflow for a disposable website. We record the exact question, explain the available choices, and keep a written summary so a reviewer can check what was actually said. This answer is test data and must not be presented as a real customer story.';
test('interview answers reach the saved Content Studio draft',async({page},info)=>{
 const reconcileBodies:{websiteId:string;articleKey:string}[]=[];
 await page.route('**/api/integrations/cms/wordpress/reconcile', async route=>{reconcileBodies.push(route.request().postDataJSON()); await route.fulfill({json:{publicationStatus:'delivered_draft'}});});
 let releaseHydration:()=>void=()=>{};
 const hydrationGate=new Promise<void>(resolve=>{releaseHydration=resolve;});
 await page.route('**/api/content/drafts?**',async route=>{await hydrationGate;await route.continue();});
 const title=`Synthetic handoff ${info.project.name} ${Date.now()}`;
 await page.goto(`/interviews?site=${fixture.mvp.websiteId}`);
 await page.getByRole('textbox',{name:'Custom interview topic',exact:true}).fill(title);
 await page.getByRole('button',{name:'Build my interview',exact:true}).click();
 await expect(page.getByText('Question 1 of 7',{exact:true})).toBeVisible();
 await page.getByRole('textbox',{name:'Your interview answer',exact:true}).fill(words);
 await page.getByRole('button',{name:'Save answer & continue →',exact:true}).click();
 for(let n=2;n<=7;n++){
  await expect(page.getByText(`Question ${n} of 7`,{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Skip this question',exact:true}).click();
 }
 await expect(page.getByRole('heading',{name:'Here is what Rebound SEO captured.',exact:true})).toBeVisible();
 await expect(page.getByRole('blockquote').filter({hasText:words}).first()).toHaveText(words);
 const {data: prior,error:readError}=await db.from('audits').select('id,website_id,requested_by,provider').eq('website_id',fixture.mvp.websiteId).eq('status','complete').order('created_at',{ascending:false}).limit(1).single();
 if(readError)throw readError;
 const {data: newer,error:newError}=await db.from('audits').insert({website_id:prior.website_id,requested_by:prior.requested_by,provider:prior.provider,status:'complete',progress:100,completed_at:new Date().toISOString()}).select('id').single();
 if(newError)throw newError;
 const {data:metric,error:metricError}=await db.from('audit_metrics').select('*').eq('audit_id',fixture.mvp.auditId).single();
 if(metricError)throw metricError;
 const {id:oldMetricId,created_at:oldMetricCreated,updated_at:oldMetricUpdated,...metricFields}=metric;
 const {error:copyError}=await db.from('audit_metrics').insert({...metricFields,audit_id:newer.id});
 if(copyError)throw copyError;
 console.log(JSON.stringify({priorAudit:prior.id,newAudit:newer.id}));
 await page.getByRole('button',{name:'Write my article from this →',exact:true}).click();
 await expect(page).toHaveURL(/\/content\?interview=/);
 const interviewId=new URL(page.url()).searchParams.get('interview');
 const {data:saved,error:savedError}=await db.from('article_drafts').select('audit_id,interview_id').eq('interview_id',interviewId);
 if(savedError)throw savedError;
 console.log(JSON.stringify({savedDraftLinks:saved,destination:page.url()}));
 await expect(page.getByText('Interview draft ready',{exact:true})).toBeVisible();
 await expect(page.getByRole('textbox',{name:'Article draft',exact:true})).toHaveValue(new RegExp(words.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));
 await expect(page.getByText('Reviewing an earlier interview draft',{exact:true})).toBeVisible();
 const box=page.getByRole('textbox',{name:'Article draft',exact:true});
 const edited=(await box.inputValue())+'\n\nSaved provenance check.';
 await box.fill(edited);
 releaseHydration();
 await expect.poll(async()=>{
  const {data}=await db.from('article_drafts').select('draft').eq('interview_id',interviewId).single();
  return data?.draft?.body;
 }).toBe(edited);
 const {data:duplicates,error:duplicateError}=await db.from('article_drafts').select('id').eq('audit_id',newer.id);
 if(duplicateError)throw duplicateError;
 expect(duplicates).toEqual([]);
 console.log('EDIT_SAVED_TO_ORIGINAL_AUDIT_WITH_NO_NEW_AUDIT_DUPLICATE');
 await page.reload();
 await expect(page.getByText('Interview draft ready',{exact:true})).toBeVisible();
 await expect(box).toHaveValue(edited);
 const {data: original,error:originalError}=await db.from('article_drafts').select('*').eq('interview_id',interviewId).single();
 if(originalError)throw originalError;
 const {error:approvalSeedError}=await db.from('article_drafts').update({draft:{...original.draft,generationStatus:'generated',generatedBy:'synthetic-local-fixture',body:edited+'\n\n'+('Synthetic audit provenance fixture content. '.repeat(380)),metaTitle:original.keyword,titleCandidates:['numbered','how_to','second_person','question','descriptive','benefit'].map(format=>({format,headline:original.keyword,metaTitle:original.keyword,score:80,rationale:'Synthetic fixture'})),qualityIssues:[],approved:true}}).eq('id',original.id);
 if(approvalSeedError)throw approvalSeedError;
 const {data: integration,error:integrationError}=await db.from('integrations').select('id').eq('website_id',fixture.mvp.websiteId).eq('provider','wordpress').single();
 if(integrationError)throw integrationError;
 const remoteUrl='https://browser-member.example/wp-admin/post.php?post=9286&action=edit';
 const {error:transferError}=await db.from('cms_transfers').insert({website_id:fixture.mvp.websiteId,integration_id:integration.id,article_key:`${prior.id}:${original.keyword}`,content_hash:'synthetic-recovery-286',remote_id:'9286',remote_edit_url:remoteUrl,status:'succeeded',publication_status:'delivered_draft',remote_status:'draft',completed_at:new Date().toISOString()});
 if(transferError)throw transferError;
 await page.reload();
 await expect(page.getByRole('button',{name:'Reopen this draft',exact:true})).toBeVisible();
 await expect(page.getByRole('link',{name:'Open WordPress editor',exact:true})).toHaveAttribute('href',remoteUrl);
 await expect(page.getByRole('button',{name:'Update WordPress draft',exact:true})).toBeVisible();
 await expect.poll(()=>reconcileBodies.some(b=>b.websiteId===fixture.mvp.websiteId && b.articleKey===`${prior.id}:${original.keyword}`)).toBe(true);
 expect(reconcileBodies.every(b=>b.articleKey!==`${newer.id}:${original.keyword}`)).toBe(true);
 await page.getByRole('button',{name:'Reopen this draft',exact:true}).click();
 await expect.poll(async()=>{const {data}=await db.from('article_drafts').select('draft').eq('id',original.id).single();return data?.draft?.approved;}).toBe(false);
 await page.reload();
 await expect(page.getByRole('button',{name:'Reopen this draft',exact:true})).toHaveCount(0);
 await expect(page.getByRole('link',{name:'Open WordPress editor',exact:true})).toHaveAttribute('href',remoteUrl);
 await page.goto(`/content?site=${fixture.mvp.websiteId}`);
 await expect(page.getByText('Reviewing an earlier interview draft',{exact:true})).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'Content creation',exact:true})).toBeVisible();
 await expect(box).toHaveCount(0);
 await page.goto(`/content?site=${fixture.alpha.websiteId}&interview=${interviewId}`);
 await expect(page.getByText('Reviewing an earlier interview draft',{exact:true})).toHaveCount(0);
 await expect(page.getByRole('link',{name:'Open WordPress editor',exact:true})).toHaveCount(0);
 await expect(page.getByRole('heading',{name:'Content creation',exact:true})).toBeVisible();
 expect(await page.locator('textarea').evaluateAll(nodes=>nodes.map(node=>(node as HTMLTextAreaElement).value))).not.toEqual(expect.arrayContaining([edited]));
 await expect(page.getByText(words,{exact:true})).toHaveCount(0);
 console.log('ORIGINAL_AUDIT_APPROVAL_AND_CMS_RECEIPT_PERSISTED; OTHER_SITE_EXCLUDED');
});
