import type { DestinyLogicResult } from "@/lib/logicaffeine";
import type { SeoAuditResult } from "@/lib/seo/types";

export const seededLogic: DestinyLogicResult = {
  growthStage: "fix_foundations",
  decisionCode: "fix_technical",
  weeklyQuest: "Fix the highest-impact technical issue",
  questCategory: "technical",
  urgency: "urgent",
  explanation: "Critical technical issues can block crawling ranking and conversions so the highest-impact issue comes first",
  keywordVerdict: "reject",
  keywordRuleId: "no_vocabulary_match",
  keywordReason: "No keyword candidate is being evaluated in this overview.",
  essentialKeyword: false,
  weeklyTaskCount: 3,
  contentTaskCount: 1,
  distributionTaskCount: 1,
  weeklyTaskManifest: ["vocabulary_review", "content_review", "primary_quest"],
  keywordEligible: false,
  keywordSearchIntent: "awareness",
  keywordPriorityTier: 0,
  keywordPriorityScore: 0,
  keywordPolicyCode: "legacy_keyword_policy",
  keywordRelevanceTier: "none",
  keywordEssential: false,
  keywordDataQuality: "intent_missing",
  keywordRuleIds: ["legacy_keyword_policy"],
  questSource: "growth_action",
  issueQuestCode: "none",
  issueDataQuality: "complete",
  weeklyTaskApprovals: [true, true, false],
  weeklyTaskTiers: [1, 1, 1],
  weeklyTaskPriorities: [1, 1, 1],
  questTransitionAllowed: true,
  questTransitionRuleId: "allow_noop",
  questVerificationStatus: "unverified",
  questSetCompletedAt: false,
  questSetVerifiedAt: false,
  questClearEvidence: true,
  questCelebration: "none",
  currentStreak: 0,
  bestStreak: 0,
  perfectWeeks: 0,
  lifetimeActiveWeeks: 0,
  planCanExport: false,
  planIdentityRuleId: "blocked_identity_mismatch",
  planKeywordTargetLow: 0,
  planKeywordTargetHigh: 0,
  planThemeCodes: ["foundation", "content_engine", "authority"],
  planScopeCode: "initial_quarter",
  planForecastConfidence: "directional",
  editorialIntentCode: 0,
  editorialSearchIntent: "awareness",
  editorialBusinessFit: 1,
  editorialOfferFit: 0,
  editorialPriorityTier: 0,
  editorialPriorityScore: 0,
  editorialKeywordIndex: 0,
  editorialAngleCode: 1,
  editorialInferredBusinessModelCode: 1,
  progressCompounding: false,
  progressCurrentNode: 1,
  progressTaskExcluded: false,
  progressTaskPhase: "ready",
  progressTaskState: "future",
  llmContentState: "not_started",
  llmPlatformState: "not_started",
  llmAuthorityState: "not_started",
  llmOutcomeState: "not_started",
  llmNextStep: 1,
  sourceProgressPercent: 0,
  sourceProofPercent: 0,
  sourceProgressState: "not_started",
  coachTaskOrder: 99,
  coachCategory: "technical-seo",
  progressDataQuality: "provider_missing",
  momentumOnboardingCurrent: 1,
  momentumOnboardingCompleted: 0,
  momentumOnboardingPercent: 0,
  momentumAuditPercent: 0,
  momentumAuditCompleted: 0,
  momentumAuditCurrent: 1,
  momentumAuditReady: false,
  momentumTimingDelayed: false,
  momentumTimingSeconds: 30,
  onboardingOneReady: false,
  onboardingTwoReady: false,
  auditHealthScore: -1,
  auditHealthCode: 0,
  auditIsPartial: false,
  rankReadingCode: 1,
  rankMovementCode: 0,
  rankMovementDelta: 0,
  rankFreshnessCode: 0,
  rankBucket: 0,
  keywordWorkspaceTab: "review",
  keywordNextStep: "review_keywords",
  articleWordIssue: true,
  articleHeadingIssue: true,
  articleHeadingKeywordIssue: true,
  articleHeadingVarietyIssue: true,
  articleBrigadeIssue: true,
  articleBrigadeSpacingIssue: false,
  articleStockIssue: false,
  articleMetaIssue: true,
  articleSourceIssue: true,
};

export const seededAudit: SeoAuditResult = {
  source: "demo",
  sourceLabel: "Demo audit data",
  domain: "example.com",
  fetchedAt: new Date(0).toISOString(),
  metrics: {
    criticalIssues: 3,
    warnings: 7,
    rankingKeywords: 7,
    newKeywords: 2,
    lostKeywords: 0,
    estimatedOrganicTraffic: 124,
    contentGaps: 8,
    reviewCount: 6,
    onPageScore: 72,
  },
  issues: [
    { code: "missing_title", label: "Missing or weak page titles", severity: "critical" },
    { code: "broken_links", label: "Broken internal links", severity: "critical" },
  ],
  competitors: [],
  keywords: [
    { keyword: "san francisco homes for families", rank: 18, searchVolume: 390, url: "https://example.com/", intent: "commercial", difficulty: 42, cpc: 3.8, opportunity: "existing_rank" },
  ],
  notices: ["This is deterministic demonstration data, not a live SEO measurement."],
};

