import Link from "next/link";
import type { KeywordMover, KeywordSummary, PanelResult } from "@/lib/rebound-core/contracts";
import { EvidenceChip, Panel, PanelHeader } from "./primitives";
import styles from "./home-dashboard.module.css";

function MoverList({ emptyText, items, tone }: { emptyText: string; items: KeywordMover[]; tone: "up" | "down" }) {
  if (!items.length) return <p className={styles.columnEmpty}>{emptyText}</p>;
  return <>{items.map((item) => <div className={styles.keywordRow} key={item.keyword}><span><strong>{item.keyword}</strong><small>Latest stored ranking observation</small></span><em data-tone={tone}>{item.delta === null ? (item.tone === "new" ? "new" : "—") : `${tone === "up" ? "▲" : "▼"}${Math.abs(Math.round(item.delta))}`}</em><b>{item.position === null ? "—" : Math.round(item.position)}</b></div>)}</>;
}

export function HomeKeywords({ result }: { result: PanelResult<KeywordSummary> }) {
  return <Panel className={styles.c12}><PanelHeader action="All keywords" href="/rank-tracker" subtitle={result.state === "ready" && result.data ? `${result.data.tracked} active tracked keywords` : "Current keyword strategy"} title="Keywords" />{result.state !== "ready" || !result.data ? <div className={styles.panelEmpty}><p>{result.message}</p><Link href="/keywords">Open keyword strategy</Link></div> : <><div className={styles.keywordStats}><div><strong>{result.data.tracked}</strong><span>Tracked</span></div><div><strong>{result.data.newlyFound}</strong><span>Newly found</span></div><div><strong>{result.data.improved}</strong><span>Improved</span></div><div><strong>{result.data.declined}</strong><span>Declined</span></div><div><strong>{result.data.lost}</strong><span>Lost</span></div></div><div className={styles.keywordBody}><section><h3>Where they sit <small>latest reading</small></h3>{result.data.buckets.map((bucket) => <div className={styles.bucket} key={bucket.label}><span>{bucket.label}</span><i><b style={{ width: `${Math.min(100, (bucket.count / Math.max(1, result.data!.tracked)) * 100)}%` }} /></i><strong>{bucket.count}</strong></div>)}</section><section><h3 data-tone="up">Winning you back <small>top movers</small></h3><MoverList emptyText="No rising keywords in the latest comparison." items={result.data.rising} tone="up" /></section><section><h3 data-tone="down">Drifting away <small>latest declines</small></h3><MoverList emptyText="No declining keywords in the latest comparison." items={result.data.declining} tone="down" /></section><section><h3 data-tone="down">Lost <small>latest comparison</small></h3><MoverList emptyText="No tracked keywords were lost in the latest comparison." items={result.data.lostItems} tone="down" /></section></div><footer className={styles.panelRead}><span><b>Read:</b> every count comes from stored rank observations; Rebound SEO does not invent a cause when the evidence does not name one.</span><EvidenceChip evidence={result.evidence[0]} /></footer></>}</Panel>;
}
