import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { PublicOnboarding } from "./public-onboarding";
import { runDestinyServerLogic } from "../lib/logicaffeine-server";

describe("PublicOnboarding momentum experience", () => {
  it("keeps the founder-led questions and presents them as a visible journey", async () => {
    const initialMomentumPolicy = await runDestinyServerLogic({ auditComplete: 0, criticalIssues: 0, warnings: 0, rankingKeywords: 0, newKeywords: 0, lostKeywords: 0, contentGaps: 0, reviewCount: 0, momentumOnboardingStep: 1 });
    const html = renderToStaticMarkup(<PublicOnboarding initialMomentumPolicy={initialMomentumPolicy} />);
    const source = readFileSync(new URL("./public-onboarding.tsx", import.meta.url), "utf8");

    expect(html).toContain("Build the momentum to be found");
    expect(html).toContain("Your path");
    expect(html).toContain("Let’s start with what is already true about your business");
    expect(html).toContain("Small steps. Real evidence. No SEO team required.");
    expect(html).toContain("Business website URL");
    expect(html).toContain("do not enter only your business name");
    expect(html).toContain("First name");
    expect(html).toContain("Last name");
    expect(html).toContain("Contact email");
    expect(html).toContain("notification center");
    expect(html).toContain("Step 1 of 3");
    expect(source).toContain('label="What do you sell?"');
    expect(source).toContain('supportText="List each product or service in plain words."');
    expect(source).toContain('placeholder="Like: tax prep, monthly accounting, payroll, CFO services."');
    expect(source).toContain('label="Who are your customers?"');
    expect(source).toContain('supportText="You probably serve a few different types. List them."');
    expect(source).toContain('placeholder="Like: restaurants, contractors, ecommerce stores, law firms."');
    expect(source).toContain('label="What problem do you fix?"');
    expect(source).toContain('supportText="What do customers want fixed, found, or made better when they come to you?"');
    expect(source).toContain(`placeholder={"Like: 'behind on the books,' 'tax deadline coming,' 'can't tell if we're profitable.'"}`);
    expect(source).not.toContain("What challenges and goals do you want to help your audience with?");
    expect(source).not.toContain('field="audienceGoals"');
    expect(source).toContain("rows={2}");
    expect(source).toContain('fieldSizing: "content"');
    expect(source).toContain("autosizeVoiceTextarea");
    expect(source).not.toContain("Step {step} of 4");
    expect(source).not.toContain("Ready to build your search baseline?");
    expect(source).not.toContain("Local market");
    expect(source).not.toContain("Search database country");
    expect(source).not.toContain("San Francisco, California");
    expect(source).not.toContain("<select");
    expect(source).toContain('aria-label={`${active ? "Stop" : "Start"} dictation for ${label}`}');
    expect(source).toContain('aria-pressed={active}');
    expect(source).toContain('active ? "Listening · tap to stop" : "Dictate"');
    expect(source).toContain("Destiny will finish after 5 seconds of silence");
    expect(source).toContain('className="voice-microphone-icon"');
    expect(html).toContain('aria-current="step"');
    expect(html).toContain("Sound off");
    expect(html).toContain("destiny-compass");
  });
});
