import { readFileSync } from "node:fs";
import { expect, test } from "@playwright/test";
const fixturePath = process.env.QA_LOCAL_BROWSER_FIXTURE;
if (!fixturePath) throw new Error("Disposable browser fixture is required.");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as { keywordWorkspaces: Record<string, { websiteId: string; auditId: string }>; outsiderSiteId: string; outsiderAuditId: string };
const keyword = "seo website migration checklist";

test("@gate new recommendations preserve decisions and hand off a saved draft", async ({ page }, testInfo) => {
  const { websiteId, auditId } = fixture.keywordWorkspaces[testInfo.project.name];
  await page.goto(`/keywords?site=${websiteId}`);
  const section = page.getByRole("region", { name: "New keyword recommendations", exact: true });
  await expect(section.getByText(keyword, { exact: true })).toBeVisible();
  await expect(section.getByRole("button", { name: "Create content", exact: true })).toBeVisible();
  await section.getByRole("button", { name: "Decline", exact: true }).click();
  await section.getByRole("button", { name: "Not now", exact: true }).click();
  await page.reload();
  await page.getByRole("tab", { name: /Declined/ }).click();
  await expect(page.getByText(keyword, { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Restore to review", exact: true }).click();
  await expect(section.getByText(keyword, { exact: true })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath(`keyword-recommendations-${testInfo.project.name}.png`), fullPage: true });
  const saved = page.waitForResponse((response) => response.url().endsWith("/api/keywords/create-content") && response.request().method() === "POST");
  await section.getByRole("button", { name: "Create content", exact: true }).click();
  const first = await saved;
  expect(first.status()).toBe(200);
  const firstDraft = await first.json();
  await expect(page).toHaveURL(new RegExp(`/content\\?site=${websiteId}&keyword=seo%20website%20migration%20checklist`));
  await expect(page.getByRole("button", { name: /1.*seo website migration checklist/ })).toBeVisible();
  await expect(page.getByText("Brief saved", { exact: true })).toBeVisible();
  const repeat = await page.request.post("/api/keywords/create-content", { data: { websiteId, auditId, keyword } });
  expect(repeat.status()).toBe(200);
  const existing = await repeat.json();
  expect(existing.id).toBe(firstDraft.id);
  expect(existing.existed).toBe(true);
  const outside = await page.request.post("/api/keywords/create-content", { data: { websiteId: fixture.outsiderSiteId, auditId: fixture.outsiderAuditId, keyword } });
  expect(outside.status()).toBe(404);
  await page.reload();
  await expect(page.getByText("Brief saved", { exact: true })).toBeVisible();
});
