import { readFileSync } from "node:fs";
import { createClient } from "@supabase/supabase-js";
import { expect, test } from "@playwright/test";

test("@gate password login and setup preserve the same user and website without email links", async ({ page, context }, testInfo) => {
  const fixture = JSON.parse(readFileSync(process.env.QA_LOCAL_BROWSER_FIXTURE!, "utf8"));
  const user = fixture.passwordUsers[testInfo.project.name];
  const destination = `/audits?site=${user.websiteId}`;
  const newPassword = `Changed-${user.password}`;
  const writes: string[] = [];
  page.on("request", request => { if (/\/auth\/v1\/(otp|recover)/.test(request.url())) writes.push(request.url()); });
  await context.clearCookies();
  await page.goto(`/login?${new URLSearchParams({ next: destination })}`);
  await expect(page.getByRole("button", { name: "Log in", exact: true })).toBeVisible();
  await page.getByLabel("Email address", { exact: true }).fill(user.email);
  await page.getByLabel("Password", { exact: true }).fill("Wrong-password-123!");
  await page.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page.locator(".login-card").getByRole("alert")).toContainText("email or password");
  await expect(page.getByLabel("Email address", { exact: true })).toHaveValue(user.email);
  await expect(page.getByLabel("Password", { exact: true })).toBeEmpty();
  expect(page.url()).not.toContain("Wrong-password");
  await page.getByLabel("Password", { exact: true }).fill(user.password);
  await page.getByRole("button", { name: "Show password", exact: true }).click();
  await expect(page.getByLabel("Password", { exact: true })).toHaveAttribute("type", "text");
  await page.getByRole("button", { name: "Hide password", exact: true }).click();
  await page.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`/audits\\?site=${user.websiteId}`));
  await expect(page.locator(`[data-workspace-website="${user.websiteId}"]`)).toBeVisible();
  await page.goto(`/account/password?${new URLSearchParams({ next: destination })}`);
  await expect(page.locator(".login-card")).toContainText(user.email);
  await page.getByLabel("New password", { exact: true }).fill(newPassword);
  await page.getByLabel("Confirm password", { exact: true }).fill("Mismatch-password!");
  await page.getByRole("button", { name: "Save password" }).click();
  await expect(page.locator(".login-card").getByRole("alert")).toContainText("do not match");
  await page.getByLabel("New password", { exact: true }).fill(newPassword);
  await page.getByLabel("Confirm password", { exact: true }).fill(newPassword);
  await page.getByRole("button", { name: "Save password" }).click();
  await expect(page.locator(".login-card").getByRole("status")).toContainText("Password saved");
  await page.getByRole("link", { name: "Return to your workspace" }).click();
  await expect(page).toHaveURL(new RegExp(user.websiteId));
  await page.getByRole("button", { name: "Sign out", exact: true }).click();
  await expect(page).toHaveURL(/\/login/);
  await page.getByLabel("Email address", { exact: true }).fill(user.email);
  await page.getByLabel("Password", { exact: true }).fill(newPassword);
  await page.getByRole("button", { name: "Log in", exact: true }).click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto(destination);
  await expect(page.locator(`[data-workspace-website="${user.websiteId}"]`)).toBeVisible();
  const outsider = await page.request.get(`/api/audits/${fixture.outsiderAuditId}`);
  expect(outsider.status()).toBe(404);
  const auth = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!, { auth: { persistSession: false, autoRefreshToken: false } });
  const confirmed = await auth.auth.signInWithPassword({ email: user.email, password: newPassword });
  expect(confirmed.error).toBeNull();
  expect(confirmed.data.user?.id).toBe(user.userId);
  expect(writes).toEqual([]);
});

test("password screens keep navigation, accessible fields and optional email fallback", async ({ page, context }) => {
  await context.clearCookies();
  await page.goto("/login?next=%2Fapp%2Fcalendar%3Fsite%3Dtest");
  await page.getByRole("link", { name: "Set or reset password" }).click();
  await expect(page.getByRole("heading", { name: "One reset. Easier logins." })).toBeVisible();
  await expect(page.locator('input[name="next"]')).toHaveValue("/app/calendar?site=test");
  await page.getByRole("link", { name: "Back to password login" }).click();
  await page.getByRole("link", { name: "Create an account" }).click();
  await expect(page.getByLabel("New password", { exact: true })).toHaveAttribute("autocomplete", "new-password");
  await expect(page.getByLabel("Confirm password", { exact: true })).toBeVisible();
  await page.getByRole("link", { name: "Back to password login" }).click();
  await page.getByRole("link", { name: "Use an email link instead" }).click();
  await expect(page.getByRole("button", { name: "Email me a sign-in link", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto("/account/password");
  await expect(page).toHaveURL(/\/login/);
  await expect(page.getByRole("button", { name: "Save password" })).toHaveCount(0);
});
